# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK


AWS_ACCESS_KEY: "AKIAJCXQU5U7U4MYS65Q"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "terrysnotes-dev"

production:
  AWS_BUCKET: "terrysnotes"